CREATE TABLE AuditLog (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    ActionType VARCHAR2(50),
    ActionDate DATE
);
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    -- Insert a record into the AuditLog table
    INSERT INTO AuditLog (TransactionID, ActionType, ActionDate)
    VALUES (:NEW.TransactionID, 'INSERT', SYSDATE);
END LogTransaction;
/
